using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace EventApplication.Models
{
    public class EventApplicationData : DropCreateDatabaseAlways<EventDB>
    {
        protected override void Seed(EventDB context)
        {
            var types = new List<EventType>
            {
                new EventType { Type = "Rock Concert" },
                new EventType { Type = "Birthday Party" },
                new EventType { Type = "Baseball Game" },
                new EventType { Type = "Basketball Game" },
                new EventType { Type = "Open Mic Night" },
                new EventType { Type = "Football Game" },
                new EventType { Type = "Swing Dance" },
                new EventType { Type = "Jazz Concert" },
                new EventType { Type = "Music Lesson" },
                new EventType { Type = "Dance Lesson" }
            };

            new List<Event>
            {
                new Event { EventType = types.Single(t => t.Type == "Rock Concert"), Title = "The Rockers: Live", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,8), EndDate = new DateTime(2019,5,8), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Rock Concert"), Title = "The Lions: Act One", Description = "The Lions playing their greatest hits", StartDate = new DateTime(2019,4,25), EndDate = new DateTime(2019,4,25), StartTime = "5:00pm", EndTime = "8:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Molly H", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Rock Concert"), Title = "The Lions: Act Two", Description = "The Lions playing their greatest hits, part 2", StartDate = new DateTime(2019,4,26), EndDate = new DateTime(2019,4,26), StartTime = "5:00pm", EndTime = "8:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Birthday Party"), Title = "Timmy's Birthday Party", Description = "A small party for Timmy's 8th birthday", StartDate = new DateTime(2019,4,27), EndDate = new DateTime(2019,4,27), StartTime = "2:00pm", EndTime = "4:00pm", MaxTickets = 25, AvailableTickets = 25, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Birthday Party"), Title = "Birthday Bash for Sarah", Description = "A party for Srah's Birthday", StartDate = new DateTime(2019,4,28), EndDate = new DateTime(2019,4,29), StartTime = "8:00pm", EndTime = "12:00am", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Jacob D", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Birthday Party"), Title = "Birthday Party for Eliza", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,4,29), EndDate = new DateTime(2019,4,29), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Baseball Game"), Title = "The Indians", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,4,30), EndDate = new DateTime(2019,4,30), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Baseball Game"), Title = "The Red Sox", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,1), EndDate = new DateTime(2019,5,1), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Baseball Game"), Title = "The Best Team", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,2), EndDate = new DateTime(2019,5,2), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Football Game"), Title = "The Browns", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,3), EndDate = new DateTime(2019,5,3), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Football Game"), Title = "The Packers", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,4), EndDate = new DateTime(2019,5,4), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Football Game"), Title = "The Patriots", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,5), EndDate = new DateTime(2019,5,5), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Swing Dance"), Title = "May Swing Dance", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,6), EndDate = new DateTime(2019,5,6), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Swing Dance"), Title = "June Swing Dance", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,7), EndDate = new DateTime(2019,5,7), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Swing Dance"), Title = "July Swing Dance", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,8), EndDate = new DateTime(2019,5,8), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Dance Lesson"), Title = "The Salsa", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,9), EndDate = new DateTime(2019,5,9), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Dance Lesson"), Title = "The Tango", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,10), EndDate = new DateTime(2019,5,10), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Dance Lesson"), Title = "The Lindyhop", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,11), EndDate = new DateTime(2019,5,11), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Music Lesson"), Title = "Guitar Lesson", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,12), EndDate = new DateTime(2019,5,12), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Music Lesson"), Title = "Drum Lessons with Tony", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,13), EndDate = new DateTime(2019,5,13), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Music Lesson"), Title = "Piano Lessons by Susie", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,3), EndDate = new DateTime(2019,5,3), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Open Mic Night"), Title = "The Coffee Coffee Open Mic Night", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,4), EndDate = new DateTime(2019,5,4), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Open Mic Night"), Title = "Andrew's Open Mic Night", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,2), EndDate = new DateTime(2019,5,2), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Open Mic Night"), Title = "Open Mic at Slymans", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,3,30), EndDate = new DateTime(2019,3,30), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Jazz Concert"), Title = "The Ladies of Cleveland Jazz Night", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,1,8), EndDate = new DateTime(2019,1,8), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Jazz Concert"), Title = "Jazz Birds", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,1), EndDate = new DateTime(2019,5,1), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Jazz Concert"), Title = "Jazzy Tunes", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,6), EndDate = new DateTime(2019,5,6), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Basketball Game"), Title = "Small Town Highschool Game", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,5), EndDate = new DateTime(2019,5,5), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Basketball Game"), Title = "The Cavs", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,3), EndDate = new DateTime(2019,5,3), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Basketball Game"), Title = "Cleveland State Basketball Game 3", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,4), EndDate = new DateTime(2019,5,4), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
            }.ForEach(a => context.Events.Add(a));
        }
    }
}