using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace EventApplication.Models
{
    public class EventApplicationData : DropCreateDatabaseIfModelChanges<EventDB>
    {
        protected override void Seed(EventDB context)
        {
            var types = new List<EventType>
            {
                new EventType { Type = "Rock Concert" },
                new EventType { Type = "Birthday Party" },
                new EventType { Type = "Baseball Game" },
                new EventType { Type = "Basketball Game" },
                new EventType { Type = "Open Mic Night" },
                new EventType { Type = "Football Game" },
                new EventType { Type = "Swing Dance" },
                new EventType { Type = "Jazz Concert" },
                new EventType { Type = "Music Lesson" },
                new EventType { Type = "Dance Lesson" }
            };

            new List<Event>
            {
                new Event { EventType = types.Single(t => t.Type == "Rock Concert"), Title = "The Rockers: Live", Description = "The greatest rock concert ever", StartDate = new DateTime(2019,5,8), EndDate = new DateTime(2019,5,8), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Rock Concert"), Title = "The Lions: Act One", Description = "The Lions playing their greatest hits", StartDate = new DateTime(2019,4,25), EndDate = new DateTime(2019,4,25), StartTime = "5:00pm", EndTime = "8:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Molly H", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Rock Concert"), Title = "The Lions: Act Two", Description = "The Lions playing their greatest hits, part 2", StartDate = new DateTime(2019,5,5), EndDate = new DateTime(2019,5,5), StartTime = "5:00pm", EndTime = "8:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Birthday Party"), Title = "Timmy's Birthday Party", Description = "A small party for Timmy's 8th birthday", StartDate = new DateTime(2019,5,9), EndDate = new DateTime(2019,5,9), StartTime = "2:00pm", EndTime = "4:00pm", MaxTickets = 25, AvailableTickets = 25, OrganizerName= "Liz Lemon", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Birthday Party"), Title = "Birthday Bash for Sarah", Description = "A party for Sarah's Birthday", StartDate = new DateTime(2019,5,6), EndDate = new DateTime(2019,5,6), StartTime = "8:00pm", EndTime = "12:00am", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Jacob D", OrganizerContactInfo = "555-123-4567", LocationCity = "Chicago", LocationState = "Illinois" },
                new Event { EventType = types.Single(t => t.Type == "Birthday Party"), Title = "Birthday Party for Eliza", Description = "Birthday party for Eliza", StartDate = new DateTime(2019,5,7), EndDate = new DateTime(2019,5,7), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Andrew H.", OrganizerContactInfo = "555-123-4567", LocationCity = "Columbus", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Baseball Game"), Title = "The Indians", Description = "The Indians Game", StartDate = new DateTime(2019,5,11), EndDate = new DateTime(2019,5,11), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Kayla R", OrganizerContactInfo = "555-123-4567", LocationCity = "Newton Falls", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Baseball Game"), Title = "The Red Sox", Description = "Red Sox Game", StartDate = new DateTime(2019,5,10), EndDate = new DateTime(2019,5,10), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Melanie T", OrganizerContactInfo = "555-123-4567", LocationCity = "Akron", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Baseball Game"), Title = "The Best Team", Description = "The Best Team Game", StartDate = new DateTime(2019,5,12), EndDate = new DateTime(2019,5,12), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Youngstown", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Football Game"), Title = "The Browns", Description = "Browns Game", StartDate = new DateTime(2019,5,13), EndDate = new DateTime(2019,5,13), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Seattle", LocationState = "Washington" },
                new Event { EventType = types.Single(t => t.Type == "Football Game"), Title = "The Packers", Description = "Packers Game", StartDate = new DateTime(2019,5,8), EndDate = new DateTime(2019,5,8), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Football Game"), Title = "The Patriots", Description = "Patriots Game", StartDate = new DateTime(2019,5,5), EndDate = new DateTime(2019,5,5), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Swing Dance"), Title = "May Swing Dance", Description = "Swing Dance in May", StartDate = new DateTime(2019,5,6), EndDate = new DateTime(2019,5,6), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Swing Dance"), Title = "June Swing Dance", Description = "Swing dance in June", StartDate = new DateTime(2019,6,7), EndDate = new DateTime(2019,6,7), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Swing Dance"), Title = "July Swing Dance", Description = "Swing dance in July", StartDate = new DateTime(2019,7,8), EndDate = new DateTime(2019,7,8), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Dance Lesson"), Title = "The Salsa", Description = "Learn the salsa", StartDate = new DateTime(2019,5,9), EndDate = new DateTime(2019,5,9), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Dance Lesson"), Title = "The Tango", Description = "Learn the Tango", StartDate = new DateTime(2019,5,6), EndDate = new DateTime(2019,5,6), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Dance Lesson"), Title = "The Lindyhop", Description = "Learn the Lindyhop", StartDate = new DateTime(2019,5,11), EndDate = new DateTime(2019,5,11), StartTime = "8:00pm", EndTime = "11:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Music Lesson"), Title = "Guitar Lesson", Description = "TLearn guitar", StartDate = new DateTime(2019,5,12), EndDate = new DateTime(2019,5,12), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Music Lesson"), Title = "Drum Lessons with Tony", Description = "Lessons with Tony", StartDate = new DateTime(2019,5,13), EndDate = new DateTime(2019,5,13), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Music Lesson"), Title = "Piano Lessons by Susie", Description = "Piano lessons taught by Susie", StartDate = new DateTime(2019,5,9), EndDate = new DateTime(2019,5,9), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Open Mic Night"), Title = "The Coffee Coffee Open Mic Night", Description = "open Mic at a coffee shop", StartDate = new DateTime(2019,5,12), EndDate = new DateTime(2019,5,12), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Open Mic Night"), Title = "Andrew's Open Mic Night", Description = "Test your Pipes at Andrew's", StartDate = new DateTime(2019,5,11), EndDate = new DateTime(2019,5,11), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Open Mic Night"), Title = "Open Mic at Slymans", Description = "Try out your talents at open mic", StartDate = new DateTime(2019,5,10), EndDate = new DateTime(2019,5,10), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Jazz Concert"), Title = "The Ladies of Cleveland Jazz Night", Description = "Celebrate the ladies of Jazz", StartDate = new DateTime(2019,5,8), EndDate = new DateTime(2019,5,8), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Jazz Concert"), Title = "Jazz Birds", Description = "Jazz music at the park", StartDate = new DateTime(2019,5,6), EndDate = new DateTime(2019,5,6), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Jazz Concert"), Title = "Jazzy Tunes", Description = "Jazz tunes in a small venue", StartDate = new DateTime(2019,5,6), EndDate = new DateTime(2019,5,6), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Basketball Game"), Title = "Small Town Highschool Game", Description = "Small Time High Game", StartDate = new DateTime(2019,5,7), EndDate = new DateTime(2019,5,7), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Basketball Game"), Title = "The Cavs", Description = "The Cavs Final Game", StartDate = new DateTime(2019,5,7), EndDate = new DateTime(2019,5,7), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
                new Event { EventType = types.Single(t => t.Type == "Basketball Game"), Title = "Cleveland State Basketball Game 3", Description = "CSU Basketball", StartDate = new DateTime(2019,5,5), EndDate = new DateTime(2019,5,5), StartTime = "3:00pm", EndTime = "4:00pm", MaxTickets = 100, AvailableTickets = 100, OrganizerName= "Annie Day", OrganizerContactInfo = "555-123-4567", LocationCity = "Cleveland", LocationState = "Ohio" },
            }.ForEach(a => context.Events.Add(a));
        }
    }
}